# Generated by Django 3.1.6 on 2021-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(blank=True),
        ),
    ]
