# Generated by Django 3.1.6 on 2021-02-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
    ]
